doctrine:
    dbal:
        default_connection:       default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            Application:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Application/Entity'
                prefix: 'Application'
                alias: Application
        controller_resolver:
            auto_mapping: true
